### ISSUE TITLE
Movie Checklist

### ISSUE THREAD

**Issue by swang** [swang/IRL#1]
- [x] 1.  The Shawshank Redemption (1994)
- [x] 2.  The Godfather (1972)
- [x] 3.  The Godfather: Part II (1974)
- [x] 4.  Pulp Fiction (1994)
- [ ] 5.  The Good, the Bad and the Ugly (1966)
- [ ] 6.  12 Angry Men (1957)
- [x] 7.  The Dark Knight (2008)
- [ ] 8.  Schindler's List (1993)
- [x] 9.  The Lord of the Rings: The Return of the King (2003)
- [x] 10. Fight Club (1999)
- [x] 11. Star Wars: Episode V - The Empire Strikes Back (1980)
- [x] 12. The Lord of the Rings: The Fellowship of the Ring (2001)
- [ ] 13. One Flew Over the Cuckoo's Nest (1975)
- [x] 14. Inception (2010)
- [x] 15. Goodfellas (1990)
- [x] 16. Star Wars (1977)
- [x] 17. Seven Samurai (1954)
- [x] 18. Forrest Gump (1994)
- [x] 19. The Matrix (1999)
- [x] 20. The Lord of the Rings: The Two Towers (2002)
- [x] 21. City of God (2002)
- [ ] 22. Once Upon a Time in the West (1968)
- [x] 23. Se7en (1995)
- [ ] 24. The Silence of the Lambs (1991)
- [ ] 25. Casablanca (1942)
- [x] 26. The Usual Suspects (1995)
- [x] 27. Raiders of the Lost Ark (1981)
- [ ] 28. Rear Window (1954)
- [ ] 29. Psycho (1960)
- [x] 30. It's a Wonderful Life (1946)
- [x] 31. Léon: The Professional (1994)
- [ ] 32. Sunset Blvd. (1950)
- [x] 33. Memento (2000)
- [x] 34. American History X (1998)
- [x] 35. Apocalypse Now (1979)
- [x] 36. Terminator 2: Judgment Day (1991)
- [x] 37. Django Unchained (2012)
- [x] 38. Saving Private Ryan (1998)
- [x] 39. Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)
- [x] 40. Alien (1979)
- [ ] 41. City Lights (1931)
- [ ] 42. North by Northwest (1959)
- [x] 43. The Dark Knight Rises (2012)
- [x] 44. Spirited Away (2001)
- [ ] 45. Modern Times (1936)
- [ ] 46. Citizen Kane (1941)
- [x] 47. The Shining (1980)
- [x] 48. Back to the Future (1985)
- [ ] 49. The Pianist (2002)
- [x] 50. The Departed (2006)
- [ ] 51. Vertigo (1958)
- [ ] 52. M (1931)
- [x] 53. American Beauty (1999)
- [ ] 54. Taxi Driver (1976)
- [ ] 55. Life Is Beautiful (1997)
- [x] 56. Paths of Glory (1957)
- [ ] 57. Double Indemnity (1944)
- [x] 58. Toy Story 3 (2010)
- [x] 59. Aliens (1986)
- [x] 60. WALL·E (2008)
- [x] 61. The Lives of Others (2006)
- [x] 62. A Clockwork Orange (1971)
- [ ] 63. The Intouchables (2011)
- [x] 64. Gladiator (2000)
- [ ] 65. The Green Mile (1999)
- [x] 66. Amélie (2001)
- [ ] 67. The Great Dictator (1940)
- [ ] 68. Lawrence of Arabia (1962)
- [x] 69. The Prestige (2006)
- [x] 70. To Kill a Mockingbird (1962)
- [x] 71. Reservoir Dogs (1992)
- [ ] 72. Das Boot (1981)
- [x] 73. Requiem for a Dream (2000)
- [ ] 74. The Third Man (1949)
- [ ] 75. The Treasure of the Sierra Madre (1948)
- [x] 76. Eternal Sunshine of the Spotless Mind (2004)
- [ ] 77. Cinema Paradiso (1988)
- [ ] 78. Once Upon a Time in America (1984)
- [x] 79. The Lion King (1994)
- [x] 80. Star Wars: Episode VI - Return of the Jedi (1983)
- [x] 81. Chinatown (1974)
- [x] 82. L.A. Confidential (1997)
- [x] 83. Full Metal Jacket (1987)
- [x] 84. Braveheart (1995)
- [ ] 85. Monty Python and the Holy Grail (1975)
- [x] 86. Oldboy (2003)
- [ ] 87. Singin' in the Rain (1952)
- [ ] 88. Some Like It Hot (1959)
- [x] 89. Amadeus (1984)
- [ ] 90. Metropolis (1927)
- [x] 91. Rashomon (1950)
- [ ] 92. Bicycle Thieves (1948)
- [x] 93. Princess Mononoke (1997)
- [x] 94. 2001: A Space Odyssey (1968)
- [ ] 95. Unforgiven (1992)
- [ ] 96. All About Eve (1950)
- [ ] 97. The Apartment (1960)
- [ ] 98. The Sting (1973)
- [x] 99. Indiana Jones and the Last Crusade (1989)
- [ ] 100.  Raging Bull (1980)
- [ ] 101.  The Bridge on the River Kwai (1957)
- [ ] 102.  Witness for the Prosecution (1957)
- [x] 103.  Die Hard (1988)
- [ ] 104.  Grave of the Fireflies (1988)
- [x] 105.  Batman Begins (2005)
- [ ] 106.  A Separation (2011)
- [x] 107.  Pan's Labyrinth (2006)
- [ ] 108.  Downfall (2004)
- [x] 109.  Yojimbo (1961)
- [ ] 110.  Mr. Smith Goes to Washington (1939)
- [ ] 111.  Snatch. (2000)
- [ ] 112.  For a Few Dollars More (1965)
- [ ] 113.  The Great Escape (1963)
- [x] 114.  Inglourious Basterds (2009)
- [x] 115.  Up (2009)
- [ ] 116.  On the Waterfront (1954)
- [ ] 117.  The Elephant Man (1980)
- [x] 118.  Toy Story (1995)
- [ ] 119.  The Seventh Seal (1957)
- [x] 120.  Heat (1995)
- [ ] 121.  The General (1926)
- [ ] 122.  The Maltese Falcon (1941)
- [x] 123.  Blade Runner (1982)
- [ ] 124.  Rebecca (1940)
- [x] 125.  Gran Torino (2008)
- [ ] 126.  Wild Strawberries (1957)
- [ ] 127.  Fargo (1996)
- [ ] 128.  The Kid (1921)
- [x] 129.  Scarface (1983)
- [x] 130.  The Big Lebowski (1998)
- [ ] 131.  Touch of Evil (1958)
- [x] 132.  Ran (1985)
- [ ] 133.  The Deer Hunter (1978)
- [ ] 134.  Cool Hand Luke (1967)
- [x] 135.  The Avengers (2012)
- [ ] 136.  The Gold Rush (1925)
- [x] 137.  Sin City (2005)
- [ ] 138.  Strangers on a Train (1951)
- [ ] 139.  It Happened One Night (1934)
- [x] 140.  No Country for Old Men (2007)
- [ ] 141.  Lock, Stock and Two Smoking Barrels (1998)
- [ ] 142.  Jaws (1975)
- [x] 143.  The Sixth Sense (1999)
- [ ] 144.  Platoon (1986)
- [x] 145.  The Thing (1982)
- [ ] 146.  Hotel Rwanda (2004)
- [x] 147.  High Noon (1952)
- [x] 148.  Casino (1995)
- [x] 149.  The Hobbit: An Unexpected Journey (2012)
- [ ] 150.  Butch Cassidy and the Sundance Kid (1969)
- [ ] 151.  Trainspotting (1996)
- [ ] 152.  The Wizard of Oz (1939)
- [x] 153.  Kill Bill: Vol. 1 (2003)
- [ ] 154.  Warrior (2011)
- [x] 155.  Annie Hall (1977)
- [x] 156.  Good Will Hunting (1997)
- [ ] 157.  The Secret in Their Eyes (2009)
- [ ] 158.  Notorious (1946)
- [x] 159.  Gone with the Wind (1939)
- [ ] 160.  The Grapes of Wrath (1940)
- [ ] 161.  Into the Wild (2007)
- [x] 162.  The King's Speech (2010)
- [ ] 163.  Life of Brian (1979)
- [x] 164.  My Neighbor Totoro (1988)
- [x] 165.  V for Vendetta (2005)
- [x] 166.  Finding Nemo (2003)
- [x] 167.  How to Train Your Dragon (2010)
- [x] 168.  Dial M for Murder (1954)
- [ ] 169.  The Big Sleep (1946)
- [ ] 170.  Network (1976)
- [x] 171.  The Terminator (1984)
- [ ] 172.  Ben-Hur (1959)
- [x] 173.  There Will Be Blood (2007)
- [x] 174.  Million Dollar Baby (2004)
- [ ] 175.  The Night of the Hunter (1955)
- [x] 176.  Stand by Me (1986)
- [x] 177.  Donnie Darko (2001)
- [x] 178.  Black Swan (2010)
- [x] 179.  Groundhog Day (1993)
- [ ] 180.  Dog Day Afternoon (1975)
- [x] 181.  Twelve Monkeys (1995)
- [ ] 182.  Life of Pi (2012)
- [ ] 183.  Amores Perros (2000)
- [x] 184.  The Bourne Ultimatum (2007)
- [ ] 185.  Mary and Max (2009)
- [ ] 186.  The 400 Blows (1959)
- [ ] 187.  Persona (1966)
- [ ] 188.  Gandhi (1982)
- [ ] 189.  The Graduate (1967)
- [ ] 190.  Howl's Moving Castle (2004)
- [ ] 191.  The Killing (1956)
- [x] 192.  The Princess Bride (1987)
- [ ] 193.  8½ (1963)
- [x] 194.  Slumdog Millionaire (2008)
- [ ] 195.  A Beautiful Mind (2001)
- [ ] 196.  The Artist (2011/I)
- [ ] 197.  The Hustler (1961)
- [ ] 198.  Who's Afraid of Virginia Woolf? (1966)
- [ ] 199.  La strada (1954)
- [ ] 200.  The Manchurian Candidate (1962)
- [x] 201.  Rocky (1976)
- [ ] 202.  Anatomy of a Murder (1959)
- [ ] 203.  The Wild Bunch (1969)
- [ ] 204.  The Exorcist (1973)
- [ ] 205.  Stalag 17 (1953)
- [ ] 206.  Rope (1948)
- [ ] 207.  Sleuth (1972)
- [ ] 208.  The Man Who Shot Liberty Valance (1962)
- [x] 209.  Barry Lyndon (1975)
- [x] 210.  The Perks of Being a Wallflower (2012)
- [ ] 211.  Memories of Murder (2003)
- [x] 212.  District 9 (2009)
- [x] 213.  Infernal Affairs (2002)
- [ ] 214.  Stalker (1979)
- [ ] 215.  Roman Holiday (1953)
- [x] 216.  The Truman Show (1998)
- [x] 217.  Pirates of the Caribbean: The Curse of the Black Pearl (2003)
- [ ] 218.  In the Name of the Father (1993)
- [ ] 219.  The Diving Bell and the Butterfly (2007)
- [x] 220.  Ip Man (2008)
- [x] 221.  Argo (2012)
- [x] 222.  Monsters, Inc. (2001)
- [x] 223.  Ratatouille (2007)
- [x] 224.  A Fistful of Dollars (1964)
- [x] 225.  Harry Potter and the Deathly Hallows: Part 2 (2011)
- [ ] 226.  A Streetcar Named Desire (1951)
- [x] 227.  Star Trek (2009)
- [x] 228.  Beauty and the Beast (1991)
- [ ] 229.  Harvey (1950)
- [ ] 230.  Rosemary's Baby (1968)
- [ ] 231.  Like Stars on Earth (2007)
- [ ] 232.  Nausicaä of the Valley of the Wind (1984)
- [ ] 233.  La Haine (1995)
- [ ] 234.  All Quiet on the Western Front (1930)
- [ ] 235.  Shutter Island (2010)
- [ ] 236.  Rain Man (1988)
- [ ] 237.  Incendies (2010)
- [ ] 238.  The Wrestler (2008)
- [ ] 239.  Mystic River (2003)
- [ ] 240.  Spring, Summer, Fall, Winter... and Spring (2003)
- [ ] 241.  Manhattan (1979)
- [ ] 242.  Nosferatu (1922)
- [ ] 243.  3 Idiots (2009)
- [x] 244.  Jurassic Park (1993)
- [ ] 245.  Papillon (1973)
- [ ] 246.  Big Fish (2003)
- [ ] 247.  Castle in the Sky (1986)
- [ ] 248.  The Untouchables (1987)
- [ ] 249.  Arsenic and Old Lace (1944)
- [ ] 250.  The Help (2011)

**Comment by swang** [comment]
Paths of Glory
