### ISSUE TITLE
Kurosawa Rewatch Checklist

### ISSUE THREAD

**Issue by swang** [swang/IRL#2]
- [ ] 1943  Sanshiro Sugata aka Judo Saga 姿三四郎 Sugata Sanshirō
- [ ] 1944  The Most Beautiful  一番美しく Ichiban utsukushiku
- [ ] 1945  Sanshiro Sugata Part II aka Judo Saga 2 續姿三四郎  Zoku Sugata Sanshirō
- [ ] 1945  The Men Who Tread on the Tiger's Tail 虎の尾を踏む男達 Tora no o wo fumu otokotachi
- [ ] 1946  No Regrets for Our Youth  わが青春に悔なし  Waga seishun ni kuinashi
- [ ] 1947  One Wonderful Sunday  素晴らしき日曜日  Subarashiki nichiyōbi
- [ ] 1948  Drunken Angel 酔いどれ天使 Yoidore tenshi
- [ ] 1949  The Quiet Duel  静かなる決闘  Shizukanaru ketto
- [ ] 1949  Stray Dog 野良犬  Nora inu
- [ ] 1950  Scandal 醜聞 Sukyandaru aka Shūbun
- [ ] 1950  Rashomon  羅生門 Rashōmon
- [ ] 1951  The Idiot 白痴 Hakuchi
- [ ] 1952  Ikiru aka To Live 生きる  Ikiru
- [ ] 1954  Seven Samurai 七人の侍 Shichinin no samurai
- [ ] 1955  I Live in Fear aka Record of a Living Being 生きものの記録  Ikimono no kiroku
- [ ] 1957  Throne of Blood aka Spider Web Castle 蜘蛛巣城 Kumonosu-jō
- [ ] 1957  The Lower Depths  どん底 Donzoko
- [ ] 1958  The Hidden Fortress 隠し砦の三悪人  Kakushi toride no san akunin
- [ ] 1960  The Bad Sleep Well  悪い奴ほどよく眠る Warui yatsu hodo yoku nemuru
- [x] 1961  Yojimbo aka The Bodyguard 用心棒  Yōjinbō
- [x] 1962  Sanjurō 椿三十郎 Tsubaki Sanjūrō
- [ ] 1963  High and Low aka Heaven and Hell  天国と地獄 Tengoku to jigoku
- [ ] 1965  Red Beard 赤ひげ  Akahige
- [ ] 1970  Dodesukaden どですかでん Dodesukaden
- [ ] 1975  Dersu Uzala デルス・ウザーラ Derusu Uzāra
- [ ] 1980  Kagemusha aka The Shadow Warrior  影武者 Kagemusha
- [ ] 1985  Ran 乱  Ran
- [ ] 1990  Dreams aka Akira Kurosawa's Dreams  夢 Yume
- [ ] 1991  Rhapsody in August  八月の狂詩曲  Hachigatsu no rapusodī aka Hachigatsu no kyōshikyoku
- [ ] 1993  Madadayo aka Not Yet  まあだだよ Mādadayo
